name: Build

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SBT
        uses: olafurpg/setup-scala@v11
        with:
          java-version: adopt@1.11

      - name: Build
        run: sbt ciBuild
